version: "3"

tasks:
  init:
    cmds:
      - docker volume create grafana-storage
      # - docker network create default
  up:
    deps:
      - init
    cmds:
      - docker compose up --remove-orphans -d

  down:
    - docker compose down

